gt_lh:
  token:
  account:
  project:

gt_my_stats:
  twitter_user:
  stack_overflow_userid:
  feedburner_uri:

gt_printio_stats:
  uri:
  key:
  profit_factor:
  ga_user:
  ga_pass:
  ga_code:

gt_printio_deploy:
  dir:

gt_commits_count:
  author:
  projects:

gt_gmail_count:
  user:
  pass:

gt_weather_current:
  code: USNY0158

gt_weather_description:
  zip: 11224